runtime: python38

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

env_variables:
  BUCKET: "sep_files"
  BACKLOOK: 92